// emit-prisma.ts — generates a schema.prisma from the control-plane spec.
// Deterministic: sorted by entity name, then attribute name.

import type { CodegenSpec } from "./types.ts";

/** Mapping from FieldType enum values to Prisma scalar types. */
const FIELD_TYPE_MAP: Record<string, string> = {
	TEXT: "String",
	TEXTAREA: "String",
	EMAIL: "String",
	PASSWORD: "String",
	NUMBER: "Float",
	DATE: "DateTime",
	DATETIME: "DateTime",
	TIME: "String",
	CHECKBOX: "Boolean",
	RADIO: "String",
	SELECT: "String",
	MULTISELECT: "String[]",
	FILE: "String",
	RICHTEXT: "String",
	COLOR: "String",
	RANGE: "Float",
	HIDDEN: "String",
	CUSTOM: "Json",
};

function toPrismaType(fieldType: string): string {
	return FIELD_TYPE_MAP[fieldType] ?? "String";
}

function toPascalCase(name: string): string {
	return name.charAt(0).toUpperCase() + name.slice(1);
}

function toCamelCase(name: string): string {
	return name.charAt(0).toLowerCase() + name.slice(1);
}

/**
 * Generate the full content of a schema.prisma for the given spec.
 */
export function emitPrismaSchema(spec: CodegenSpec): string {
	const lines: string[] = [];

	// Preamble
	lines.push(`// Generated by DTFS codegen — do not edit by hand.`);
	lines.push(`// Source project: ${spec.project.slug}`);
	lines.push(``);

	// Generator
	lines.push(`generator client {`);
	lines.push(`  provider = "prisma-client-js"`);
	lines.push(`  output   = "../generated/prisma"`);
	lines.push(`}`);
	lines.push(``);

	// Datasource
	lines.push(`datasource db {`);
	lines.push(`  provider = "postgresql"`);
	lines.push(`  url      = env("DATABASE_URL")`);
	lines.push(`}`);
	lines.push(``);

	// Build lookup maps
	const entityById = new Map(spec.entities.map((e) => [e.id, e]));

	// Relations grouped by fromEntityId
	const relationsByFrom = new Map<string, typeof spec.entityRelations>();
	for (const rel of spec.entityRelations) {
		const list = relationsByFrom.get(rel.fromEntityId) ?? [];
		list.push(rel);
		relationsByFrom.set(rel.fromEntityId, list);
	}

	// Sort entities by name for determinism
	const sortedEntities = [...spec.entities].sort((a, b) => a.name.localeCompare(b.name));

	for (const entity of sortedEntities) {
		const modelName = toPascalCase(entity.name);
		lines.push(`model ${modelName} {`);

		// Always emit an id field
		lines.push(`  id        String   @id @default(cuid())`);
		lines.push(`  createdAt DateTime @default(now())`);
		lines.push(`  updatedAt DateTime @updatedAt`);
		lines.push(``);

		// Sort attributes by name
		const sortedAttrs = [...entity.attributes].sort((a, b) => a.name.localeCompare(b.name));
		for (const attr of sortedAttrs) {
			const prismaType = toPrismaType(attr.type);
			const optional = attr.required ? "" : "?";
			// For array types (MULTISELECT), remove the ? — arrays can't be optional in Prisma that way
			const isArray = prismaType.endsWith("[]");
			const typeStr = isArray ? prismaType : `${prismaType}${optional}`;
			const unique = attr.unique ? " @unique" : "";
			const padding = " ".repeat(Math.max(1, 10 - attr.name.length));
			lines.push(`  ${attr.name}${padding}${typeStr}${unique}`);
		}

		// Outgoing relations for this entity
		const outgoing = (relationsByFrom.get(entity.id) ?? []).sort((a, b) =>
			a.name.localeCompare(b.name),
		);
		if (outgoing.length > 0) {
			lines.push(``);
			for (const rel of outgoing) {
				const toEntity = entityById.get(rel.toEntityId);
				if (!toEntity) continue;
				const toModel = toPascalCase(toEntity.name);
				const fkField = rel.fromField ?? `${toCamelCase(toEntity.name)}Id`;

				if (rel.kind === "MANY_TO_MANY") {
					lines.push(`  ${rel.name} ${toModel}[]`);
				} else if (rel.kind === "ONE_TO_ONE") {
					const opt = rel.required ? "" : "?";
					lines.push(`  ${fkField} String${opt}`);
					lines.push(
						`  ${toCamelCase(toEntity.name)} ${toModel}${opt} @relation(fields: [${fkField}], references: [id])`,
					);
				} else {
					// ONE_TO_MANY — from side holds FK
					const opt = rel.required ? "" : "?";
					lines.push(`  ${fkField} String${opt}`);
					lines.push(
						`  ${toCamelCase(toEntity.name)} ${toModel}${opt} @relation(fields: [${fkField}], references: [id])`,
					);
				}
			}
		}

		lines.push(`}`);
		lines.push(``);
	}

	return lines.join("\n");
}
